#+TITLE: Config
#+PROPERTY: header-args :tangle ./config.el
* Global
** Custom mode assignment
Enable proper syntax highlighting for xmobarrc.
#+BEGIN_SRC elisp
(add-to-list 'auto-mode-alist '("\\xmobarrc" . haskell-mode))
#+END_SRC
** Global Keybindings
*** C-a/C-e
Making C-a and C-e behave like I expect them to.
#+begin_src elisp
(map! :n "C-e"                          #'move-end-of-line)
(map! :mode org-mode
      :n "C-e"                          #'org-end-of-line)
#+end_src
*** Org-capture
Switching the bindings for org-capture and scratch buffer(which I almost never use).
#+BEGIN_SRC elisp
(map! :leader
      :desc "Org capture"           "x" #'org-capture
      :desc "Pop up scratch buffer" "X" #'doom/open-scratch-buffer)
#+END_SRC
*** Recentf
Making recentf available via my preferred emacs bindings.
#+begin_src elisp
(map! :n "C-x C-r"                      #'counsel-recentf)
#+end_src
** Identity
#+BEGIN_SRC elisp
(setq user-full-name "Elia Nolz"
      user-mail-address "eliarnolz@gmail.com")
#+END_SRC
** Look
Set fonts and theme.

Doom exposes five (optional) variables for controlling fonts in Doom. Here
are the three important ones:
+ `doom-font'
+ `doom-variable-pitch-font'
+ `doom-big-font' -- used for `doom-big-font-mode'
They all accept either a font-spec, font string ("Input Mono-12"), or xlfd
font string.
#+BEGIN_SRC elisp
(cond
 ((or (string= (system-name) "Nanocore")
     (string= (system-name) "Nanoplane"))
  (setq doom-font (font-spec :family "Hack" :size 12.0)))
 ((string= (system-name) "Nanorocket")
  (setq doom-font (font-spec :family "Fira Code Retina" :size 11.5)
        doom-variable-pitch-font (font-spec :family "Overpass"))))
(setq doom-theme 'doom-nord)
(setq display-line-numbers-type nil)
#+END_SRC
** Mouse
Disable highlighting of e.g. org-agenda items with mouse hover.
#+BEGIN_SRC elisp
(setq mouse-highlight nil)
#+END_SRC
** Small stuff
Handling two buffers with the same name via longer displayed path rather than name<2>.
#+BEGIN_SRC elisp
(setq-default uniquify-buffer-name-style 'forward)
#+END_SRC
Unicode instead of ...
#+BEGIN_SRC elisp
(setq truncate-string-ellipsis "…")
#+END_SRC
Display battery charge when available.
#+BEGIN_SRC elisp
(unless (equal "Battery status not available" (battery))
  (display-battery-mode 1))
#+END_SRC
Iterate through camelCase words.
#+BEGIN_SRC elisp
;; (global-subword-mode 1)
#+END_SRC
* Anki
#+BEGIN_SRC elisp
(use-package! anki-editor
  :after org
  :bind (:map org-mode-map
         ("<f12>" . anki-editor-cloze-region-auto-incr)
         ("<f11>" . anki-editor-cloze-region-dont-incr)
         ("<f10>" . anki-editor-reset-cloze-number)
         ("<f9>"  . anki-editor-push-tree))
  :hook (org-capture-after-finalize . anki-editor-reset-cloze-number)
  :config
  (setq anki-editor-create-decks t
        ankid-editor-org-tags-as-anki-tags t)
  (defun anki-editor-cloze-region-auto-incr (&optional arg)
    "Cloze region without hint and increase card number."
    (interactive)
    (anki-editor-cloze-region my-anki-editor-cloze-number "")
    (setq my-anki-editor-cloze-number (1+ my-anki-editor-cloze-number))
    (forward-sexp))
  (defun anki-editor-cloze-region-dont-incr (&optional arg)
    "Cloze region without hint using the previous card number."
    (interactive)
    (anki-editor-cloze-region (1- my-anki-editor-cloze-number) "")
    (forward-sexp))
  (defun anki-editor-reset-cloze-number (&optional arg)
    "Reset cloze number to ARG or 1."
    (interactive)
    (setq my-anki-editor-cloze-number (or arg 1)))
  (defun anki-editor-push-tree ()
    "Push all notes under a tree."
    (interactive)
    (anki-editor-push-notes '(4))
    (anki-editor-reset-cloze-number))
  (anki-editor-reset-cloze-number))
#+END_SRC
* Calc
Setting up a keybinding for calc(best calculator).
#+BEGIN_SRC elisp
(map! :leader
      :prefix "o"
      :n "c" 'calc)
#+END_SRC
* Eshell
Set a new prompt for eshell(function needs to be regexp-compliant to allow tab completion of commands).
#+BEGIN_SRC elisp
;; (setq eshell-prompt-function ...)
#+END_SRC
** Aliases
Defining eshell aliases.
#+BEGIN_SRC elisp
(after! eshell
  (set-eshell-alias!
   "la" "ls -al"
   "brctl" "brightnessctl set $1"
   "mymap" "xkbcomp -I/home/lycheese/.config/xkb /home/lycheese/.config/xkb/myMap $DISPLAY"))
#+END_SRC
** Keybingings
Binding useful shortcuts for navigation.
#+BEGIN_SRC elisp
;; (map! :mode eshell-mode
;;       :n "J" 'eshell-next-prompt
;;       :n "K" 'eshell-previous-prompt
;;       :n "?" '+eshell/search-history)
#+END_SRC
* IRC
** Discord
#+BEGIN_SRC elisp
;; (after! circe)
#+END_SRC
* Languages
** Elisp
Make ert easier to reach.
#+BEGIN_SRC elisp
(map! :map emacs-lisp-mode-map
      (:localleader
       :prefix "e"
       :n "t" 'ert))
#+END_SRC
** Projectile
?
#+BEGIN_SRC elisp
(setq projectile-project-search-path '("~/dev" "~/Nextcloud"))
#+END_SRC
* Mail
** General
Append mu4e to the open menu.
#+BEGIN_SRC elisp
(map! :leader
      :prefix "o"
      :n "m" 'mu4e)
#+END_SRC

Setting up mail directories.
#+BEGIN_SRC elisp
(after! mu4e
  (setq mu4e-root-maildir "~/Mail")
  (setq mu4e-attachment-dir "~/Downloads"))
#+END_SRC

Setting up message deletion behaviour for gmail while excluding the non-gmail addresses.
#+BEGIN_SRC elisp
(after! mu4e
  (setq mu4e-sent-messages-behavior
        (lambda ()
          (if (string= (message-sendmail-envelope-from) "nb191@stud.uni-heidelberg.de")
              'sent
            'delete))))
#+END_SRC

Set color luminance to enhance contrast for html emails as they often tend to be unreadable in mu4e.
#+BEGIN_SRC elisp
(after! mu4e
  (setq shr-color-visible-luminance-min 80))
#+END_SRC

Always ask which context should be used when composing new mail.
#+BEGIN_SRC elisp
(after! mu4e
  (setq mu4e-compose-context-policy 'ask))
#+END_SRC
** Contexts
Simplified mu4e contexts
#+BEGIN_SRC elisp
(set-email-account! "nb191"
                    '((mu4e-sent-folder       . "/nb191/Sent")
                      (mu4e-drafts-folder     . "/nb191/Drafts")
                      (mu4e-trash-folder      . "/nb191/Trash")
                      (smtpmail-smtp-user     . "nb191@stud.uni-heidelberg.de")
                      (user-mail-address      . "nb191@stud.uni-heidelberg.de")
                      (mu4e-compose-signature . "Elia Nolz")))
#+END_SRC
** Prettifying
No astrisks and angle brackets in the mu4e main view.
Needs to be an advice rather than an after-block because =mu4e-main-action-string= is called by evil-collection-mu4e in doom's usepackage.
#+BEGIN_SRC elisp
(defadvice! mu4e~main-action-prettier-str (str &optional func-or-shortcut)
  "Highlight the first occurrence of [.] in STR.
If FUNC-OR-SHORTCUT is non-nil and if it is a function, call it
when STR is clicked (using RET or mouse-2); if FUNC-OR-SHORTCUT is
a string, execute the corresponding keyboard action when it is
clicked."
  :override #'mu4e~main-action-str
  (let ((newstr
         (replace-regexp-in-string
          "\\[\\(..?\\)\\]"
          (lambda(m)
            (format "%s"
                    (propertize (match-string 1 m) 'face '(mode-line-emphasis bold))))
          (replace-regexp-in-string "\t\\*" "\t⚫" str)))
        (map (make-sparse-keymap))
        (func (if (functionp func-or-shortcut)
                  func-or-shortcut
                (if (stringp func-or-shortcut)
                    (lambda()(interactive)
                      (execute-kbd-macro func-or-shortcut))))))
    (define-key map [mouse-2] func)
    (define-key map (kbd "RET") func)
    (put-text-property 0 (length newstr) 'keymap map newstr)
    (put-text-property (string-match "[A-Za-z].+$" newstr)
                       (- (length newstr) 1) 'mouse-face 'highlight newstr)
    newstr))

(setq evil-collection-mu4e-end-region-misc "quit")
#+END_SRC
* Org
** Setup
Setting the org directory.
#+BEGIN_SRC elisp
(setq org-directory "~/Nextcloud/org/")
#+END_SRC
Useless pretty symbols for folded headings.
#+BEGIN_SRC elisp
;; (setq org-ellipsis "⤵")
#+END_SRC
Less eye candy.
#+BEGIN_SRC elisp
(remove-hook 'org-mode-hook #'org-superstar-mode)
#+END_SRC
Personal todo keywords.

[[https://orgmode.org/manual/Tracking-TODO-state-changes.html][Tracking of TODO state changes]]:
- ! for a timestamp
- @ for a note with a timestamp
- @/! for a note with a timestamp when entering the state and a timestamp when leaving the state
- The variable =org-log-into-drawer= can be set to log this state changes into a specific drawer instead of inserting it directly into the body of the respective heading. The recommended setting for this is =LOGBOOK=.
#+BEGIN_SRC elisp
(after! org
  (setq org-todo-keywords '((sequence "TODO(t)" "PROJ(p)" "STRT(s@)" "WAIT(w@/!)" "HOLD(h@/!)" "FILE(f@)" "|" "DONE(d!)" "KILL(k@)")
                            (sequence "[ ](T)" "[-](S)" "[?](W)" "|" "[X](D)"))
        org-log-into-drawer "LOGBOOK")
  (add-to-list 'org-todo-keyword-faces '("FILE" . +org-todo-active)))
#+END_SRC
** Modules
*** deft
Setup deft directory tree with recursive searching.
#+BEGIN_SRC elisp
(setq deft-directory "~/Nextcloud/org/"
      deft-recursive t)
#+END_SRC
*** evil-org
Continue list when inserting a new line with =o=.
#+BEGIN_SRC elisp
(setq evil-org-special-o/O '(table-row item))
#+END_SRC
Use =g o= to insert new headline even when not on a headline and switch to insert mode.
#+BEGIN_SRC elisp
(defun org-new-heading-and-insert ()
  "Executes org-ctrl-c-ret and places pointer in insert mode"
  (interactive)
  (org-ctrl-c-ret)
  (evil-insert 0))

(map! :map org-mode-map
      (:prefix "g"
       :n "o" 'org-new-heading-and-insert))
#+END_SRC
*** org-agenda
Detect all files for org agenda.
#+BEGIN_SRC elisp
(after! org-agenda
  (setq org-agenda-files (directory-files-recursively org-directory "org$")
        org-agenda-skip-scheduled-if-done t
        org-agenda-skip-deadline-if-done t
        org-agenda-include-deadlines t
        org-agenda-block-separator nil
        org-agenda-compact-blocks t
        org-agenda-start-day nil
        org-agenda-span 'day
        org-agenda-start-on-weekday nil))
#+END_SRC
Make org-agenda save org-files on quit and switching by RET.
#+BEGIN_SRC elisp
(general-advice-add '(org-agenda-quit org-agenda-switch-to)  :before 'org-save-all-org-buffers)
#+END_SRC
**** org-habit
#+BEGIN_SRC elisp
(after! org
  (add-to-list 'org-modules 'org-habit))
(map! :map evil-org-agenda-mode-map
      :prefix "c"
      :n "t" #'counsel-org-tag-agenda)
#+END_SRC
**** org-super-agenda
#+BEGIN_SRC elisp
(use-package! org-super-agenda
  :hook (org-agenda-mode . org-super-agenda-mode)
  :init
  (setq org-super-agenda-groups
        '((:name "Today"
           :time-grid t
           :todo "TODAY"
           :order 1)
          (:name "Important"
           :tag "Wohnheim"
           :order 1)
          (:name "Critically overdue"
           :deadline past
           :order 0)
          (:name "University Stuff"
           :tag "Uni"
           :order 3)
          (:name "Habits"
           :habit t
           :order 2)
          (:name "Completed projects that still need to be filed away"
           :todo "FILE"
           :order 95)
          (:name "Scheduled Projects"
           :todo "PROJ"
           :order 97)
          (:name "Emacs Stuff"
           :tag "Emacs"
           :order 98)
          (:name "Reading"
           :tag "Books"
           :order 96)
          (:name "Overdue"
           :scheduled past
           :not (:todo "PROJ")
           :order 1))))
#+END_SRC
Removing the org-super-agenda keybindings because they overwrite the evil ones.
#+BEGIN_SRC elisp
(after! org-super-agenda
  (setq org-super-agenda-header-map (make-sparse-keymap)))
#+END_SRC
*** org-archive
#+BEGIN_SRC elisp
(setq org-archive-location "~/Nextcloud/org/archive.org::* From %s")
#+END_SRC
*** org-babel
Needed for #+BIND statements, but can be set locally.
#+BEGIN_SRC elisp
;; (setq org-export-allow-bind-keywords t)
#+END_SRC
Inactive Code:
#+BEGIN_SRC elisp
;; org-bable
;; enables code highlighting in latex exports
;; (setq org-latex-packages-alist '("" "minted"))
;; allows manipulation of verbatim blocks like #+RESULTS with a function
;; (setq org-export-filter-verbatim-functions '())
#+END_SRC
**** latex
Enable highlighting for org-babel code-exports to latex documents.
#+BEGIN_SRC elisp
(setq org-latex-listings 'minted)
#+END_SRC
Modified pdflatex-commands for =minted= compatibility.
#+BEGIN_SRC elisp
(setq org-latex-pdf-process
      '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
        "bibtex %b"
        "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
        "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
#+END_SRC
Not sure why I added this...
#+BEGIN_SRC elisp
(setq org-latex-default-table-mode 'table)
#+END_SRC
*** org-caldav
#+BEGIN_SRC elisp
(after! org-caldav
  :config
  (setq org-caldav-url         "https://nohneltina.net/remote.php/dav/calendars/lycheese/"
        org-caldav-calendar-id "org-agenda"
        org-caldav-inbox       "~/Nextcloud/org/inbox-caldav.org"
        org-caldav-files       (directory-files-recursively org-directory "org$")
        org-icalendar-timezone "Europe/Berlin"))
#+END_SRC
*** org-capture
Useful capture templates for japanese vocab, contacts, tasks and more.
#+BEGIN_SRC elisp
(after! org-capture
  (setq org-capture-templates
        '(("t" "Tasks")
          ("tt" "Task for today" entry
           (file+olp+datetree "notes.org")
           "* %^{Select type|TODO|WAIT|HOLD|KILL|DONE} %^{Task} %^G\n SCHEDULED: %t\n%?\nAdded: %U")
          ("ts" "Scheduled task" entry
           (file+olp+datetree "notes.org")
           "* %^{Select type|TODO|WAIT|HOLD|KILL|DONE} %^{Task} %^G\n SCHEDULED: %^t\n%?\nAdded: %U")
          ("td" "Scheduled task with deadline" entry
           (file+olp+datetree "notes.org")
           "* %^{Select type|TODO|WAIT|HOLD|KILL|DONE} %^{Task} %^G\n DEADLINE: %^t\n%?\nAdded: %U")
          ("tn" "Not scheduled task" entry
           (file+olp+datetree "notes.org")
           "* %^{Select type|TODO|WAIT|HOLD|KILL|DONE} %^{Task} %^G\n%?\nAdded: %U")

          ("p" "Project" entry
           (file+olp+datetree "notes.org")
           "* PROJ %^{Project} %^G\n%?\nAdded: %U")

          ("n" "Notes" entry
           (file+olp+datetree "notes.org")
           "* %U %^{Title} %^G\n%?")

          ("c" "Contacts")
          ("cp" "Private contact" entry
           (file+olp "contacts.org" "Kontakte" "Privat")
           "* %^{Name}\n Email: %^{Email}\nTelephone: %^{Telephone number}\n** TODO Geburtstag von %\\1\nSCHEDULED: %^{Birthday}t"
           :immediate-finish t)
          ("cf" "Family contact" entry
           (file+olp "contacts.org" "Kontakte" "Familie")
           "* %^{Name}\n Email: %^{Email}\nTelephone: %^{Telephone number}\n** TODO Geburtstag von %\\1\nSCHEDULED: %^{Birthday}t"
           :immediate-finish t)
          ("cw" "Work contact" entry
           (file+olp "contacts.org" "Kontakte" "Arbeit")
           "* %^{Name}\n Email: %^{Email}\nTelephone: %^{Telephone number}\n** TODO Geburtstag von %\\1\nSCHEDULED: %^{Birthday}t"
           :immediate-finish t)
          ("co" "Other contacts" entry
           (file+olp "contacts.org" "Kontakte" "Andere")
           "* %^{Name}\n Email: %^{Email}\nTelephone: %^{Telephone number}\n** TODO Geburtstag von %\\1\nSCHEDULED: %^{Birthday}t"
           :immediate-finish t)
          ("cn" "New contact template" entry
           (file+olp "contacts.org" "Kontakte" "Testbereich")
           "* %^{Name}\n:PROPERTIES:\n:EMAIL: %^{Email}\n:PHONE: %^{Telefon}\n:ALIAS: %^{Alias}\n:ADDRESS: %^{Adresse}\n:END:\n** TODO Geburtstag von %\\1\nSCHEDULED:%^{Geburtstag}t %?")

          ("j" "Japanese vocab")
          ("jn" "Japanese noun" entry
           (file+olp+datetree "hobby/japanese.org" "Vocab" "Noun")
           "* %^{Japanese} \[%^{Reading}\] %^g\nTranslation: %^{English}\nNew Kanji?: %^{New Kanji?|Yes|No}\nAdditional stuff: %?")
          ("jv" "Japanese verb" entry
           (file+olp+datetree "hobby/japanese.org" "Vocab" "Verb")
           "* %^{Japanese} \[%^{Reading}\] %^g\nTranslation: %^{English}\nNew Kanji?: %^{New Kanji?|Yes|No}\nType: %^{Ichidan or Godan?|Ichidan|Godan} and %^{Transitivity|Transitive|Intransitive}\nAdditional stuff: %?")
          ("ja" "Japanese adjective" entry
           (file+olp+datetree "hobby/japanese.org" "Vocab" "Adjective")
           "* %^{Japanese} \[%^{Reading}\] %^g\nTranslation: %^{English}\nNew Kanji?: %^{New Kanji?|Yes|No}\nType: %^{i-adj or na-adj|i-adj|na-adj}\nAdditional stuff: %?")
          ("jo" "Other japanese vocab" entry
           (file+olp+datetree "hobby/japanese.org" "Vocab" "Other")
           "* %^{Japanese} \[%^{Reading}\] %^g\nTranslation: %^{English}\nNew Kanji?: %^{New Kanji?|Yes|No}\nAdditional stuff: %?"))))
#+END_SRC
*** org-journal
#+BEGIN_SRC elisp
;; (after! org-journal
;;   :config
;;   (setq org-journal-file-type 'yearly
;;         org-journal-date-format "%A, %d %B %Y"))
#+END_SRC
*** org-roam
#+BEGIN_SRC elisp
(setq org-roam-directory "~/Nextcloud/org/roam")
#+END_SRC
* Secrets
=auth-sources= _MUST_ be a list!
#+BEGIN_SRC elisp
;; (setq auth-sources '("~/.authinfo.gpg"))
(setq auth-sources '(password-store))
(setq auth-source-debug 'trivia)
#+END_SRC
** Pass
Binding keys for pass and ivy-pass.
#+BEGIN_SRC elisp
(map! :leader
      :prefix "o"
      :desc "Copy password to kill ring" "s" 'ivy-pass
      :desc "Open password manager"      "S" 'pass)
#+END_SRC
